### PR TITLE
adds more screenshots images for readme file

### PR DESCRIPTION
**Pull request by meskyA**

### CODE REVIEW

**Review by FormulaXYZ — DISMISSED** [review]

**Comment by FormulaXYZ** [comment]
very good but we still need more screen shots

**Review by FormulaXYZ — DISMISSED** [review]

**Review by mconanan — APPROVED** [review]
tested frontend-test on my local and everything works!

**Review by FormulaXYZ — APPROVED** [review]

**Comment by FormulaXYZ** [comment]
Great Job

**Comment by FormulaXYZ** [comment]
it's all good.

**Pull request merged**
